Really make kwargs a dictionary of keyword parameters
Fixes the error:
TypeError: BaseHQQHFModel.create_model() missing 1 required positional argument: 'kwargs'
that prevents loading HF models